/*
    TR4QT - An Amateur Radio Contesting Logger inspired by TR4W and TRLog.
    Copyright (C) 2026 Thomas M. Schaefer NY4I ny4i@ny4i.com

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

#ifndef KEYERCWSENDER_H
#define KEYERCWSENDER_H

#include "CWSender.h"

namespace TR4QT {

class KeyerController;

/**
 * CW sender implementation using an external keyer device (WinKeyer).
 *
 * Delegates text sending to the KeyerController, which manages the
 * WinKeyer hardware in a worker thread. The WinKeyer generates Morse
 * code in hardware from text characters.
 *
 * For paddle-only devices (HaliKey), CW is generated by the software
 * IambicKeyer → RadioController path, not through this sender.
 */
class KeyerCWSender : public CWSender {
    Q_OBJECT

public:
    explicit KeyerCWSender(KeyerController* keyer, QObject* parent = nullptr);
    ~KeyerCWSender() override = default;

    // CWSender interface
    State state() const override;
    bool isAvailable() const override;
    QString backendName() const override { return "External Keyer"; }

    int wpm() const override;
    void setWpm(int wpm) override;

public slots:
    void send(const QString& text) override;
    void stop() override;

private:
    KeyerController* m_keyer;
    int m_wpm = 25;
    State m_state = State::Idle;
};

} // namespace TR4QT

#endif // KEYERCWSENDER_H
